[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SCALES-DRP"
authors = [{name = "Steph Sallum", email = ""}]
dynamic = ["version", "description"]
